# Generated by Django 5.2.14 on 2026-05-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('application_link', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
